name: Auto-update Casks

on:
  # Check for updates daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for cask updates
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          brew tap ${{ github.repository }}
          echo "Checking athas-editor for updates..."
          
          # Get current version from cask
          CURRENT_VERSION=$(brew info --cask athas-editor --json=v2 | jq -r '.casks[0].version')
          echo "Current version: $CURRENT_VERSION"
          
          # Get latest version from GitHub
          LATEST_VERSION=$(curl -s https://api.github.com/repos/athasdev/athas/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "Latest version: $LATEST_VERSION"
          
          if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
            echo "athas-editor is up to date"
          else
            echo "Update available for athas-editor: $CURRENT_VERSION -> $LATEST_VERSION"
            
            # Download and calculate sha256 for both architectures
            AARCH64_URL="https://github.com/athasdev/athas/releases/download/v${LATEST_VERSION}/Athas_${LATEST_VERSION}_aarch64.dmg"
            X64_URL="https://github.com/athasdev/athas/releases/download/v${LATEST_VERSION}/Athas_${LATEST_VERSION}_x64.dmg"
            
            echo "Downloading aarch64 version..."
            curl -sL "$AARCH64_URL" -o /tmp/athas_aarch64.dmg
            AARCH64_SHA256=$(shasum -a 256 /tmp/athas_aarch64.dmg | awk '{print $1}')
            echo "aarch64 sha256: $AARCH64_SHA256"
            
            echo "Downloading x64 version..."
            curl -sL "$X64_URL" -o /tmp/athas_x64.dmg
            X64_SHA256=$(shasum -a 256 /tmp/athas_x64.dmg | awk '{print $1}')
            echo "x64 sha256: $X64_SHA256"
            
            # Update the cask file
            CASK_FILE="Casks/athas-editor.rb"
            sed -i "s/version \".*\"/version \"$LATEST_VERSION\"/" "$CASK_FILE"
            sed -i "s/sha256 arm:   \".*\",/sha256 arm:   \"$AARCH64_SHA256\",/" "$CASK_FILE"
            sed -i "s/intel: \".*\"/intel: \"$X64_SHA256\"/" "$CASK_FILE"
            
            echo "Updated cask file"
          fi
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "chore: update cask(s) to latest version"
          title: "chore: update cask(s) to latest version"
          body: |
            Automated cask version update.
            
            This PR was automatically generated by the auto-update-casks workflow.
          branch: auto-update-casks
          delete-branch: true
