name: Auto-update Casks

on:
  # Check for updates daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for cask updates
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          brew tap ${{ github.repository }}
          echo "Checking athas-editor for updates..."
          if brew livecheck --cask athas-editor | grep -q "latest"; then
            echo "athas-editor is up to date"
          else
            echo "Update available for athas-editor"
            brew bump-cask-pr --write-only --no-browse athas-editor || echo "Bump failed or no update needed"
          fi
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "chore: update cask(s) to latest version"
          title: "chore: update cask(s) to latest version"
          body: |
            Automated cask version update.
            
            This PR was automatically generated by the auto-update-casks workflow.
          branch: auto-update-casks
          delete-branch: true
